on: push

#  schedule:
#  - cron: 0 12 * * *

name: Data

jobs:
  Data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test script
        run: docker run -v `pwd`:/mnt appsilon/paraproj:1.3 bash -c "/mnt/run.R"
        env:
          TEST_ENV_VAR: ${{ secrets.TEST_ENV_VAR }}


