on: push

#  schedule:
#  - cron: 0 12 * * *

name: Data

jobs:
  Data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: satackey/action-docker-layer-caching@v0.0.8
        continue-on-error: true
      - name: Run test script
        run: docker run -v `pwd`:/mnt -e TEST_ENV_VAR=${{ secrets.TEST_ENV_VAR }} appsilon/paraproj:1.3 bash -c "Rscript '/mnt/run.R'"

